BatteryStateDatabase: Set exportSchema to false
Log:
Output:
packages/apps/Settings/src/com/android/settings/fuelgauge/batteryusage/db/BatteryStateDatabase.java:35: error: Schema export directory was not provided to the annotation processor so Room cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument by applying the Room Gradle plugin (id 'androidx.room') OR set exportSchema to false.
public abstract class BatteryStateDatabase extends RoomDatabase {
                      ^

Change-Id: I493d978ee204761e93fb177680bd102c30b45e9c
Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>
Signed-off-by: Ghosuto <clash.raja10@gmail.com>